version: 2
updates:
  - package-ecosystem: composer
    directory: "/process"
    schedule:
      interval: daily
    commit-message:
      prefix: "⬆️"
    open-pull-requests-limit: 10
    assignees:
      - "RobinLinde"

  - package-ecosystem: npm
    directory: "/website"
    schedule:
      interval: daily
    commit-message:
      prefix: "⬆️"
    open-pull-requests-limit: 10
    assignees:
      - "RobinLinde"