name: Update data

on:
  # Run every second of the month at 5:00 UTC
  schedule:
    - cron: '0 5 2 * *'
  push:
    paths:
      - '.github/workflows/update-data.yml'
      - 'scripts/**'
  pull_request:
    paths:
      - '.github/workflows/update-data.yml'
      - 'scripts/**'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Update data
        run: npm run fetch-data
        env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }}

      - name: Commit changes
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add data/*
          git commit -m "🗃 Update data"

      - name: Push
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name != 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
